spring:
  datasource:
    url: jdbc:h2:mem:my-awesome-db
    username: sa
    password:
    initialization-mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2